namespace: external-dns
resources:
  - ../base
  - resource/Secret/dns-provider-credentials.yaml
patches:
  - path: patch/Deployment/external-dns.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: external-dns
