apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
type: Opaque
data:
  webserver-password: "{{ .Values.powerdns.webserver.password | toString | b64enc }}"
  api-key: "{{ .Values.powerdns.api.key | toString | b64enc }}"
