apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume-claim
  {{- if .Values.persistence.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
