apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.database_service_type }}
  clusterIP: {{ .Values.global.database_clusterIP }}
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.database_port }}
      targetPort: {{ .Values.global.database_port }}
