---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  storageClassName: local
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
