---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: media
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  storageClassName: local
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: {{ .Values.mediaVolume.hostPath }}
    type: DirectoryOrCreate
