kind: MachineRegistration
apiVersion: elemental.cattle.io/v1beta1
metadata:
  name: default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        automatic: true
        device: /dev/sda
        eject-cd: true
        reboot: true
        debug: true
