# Default values for baremetal-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:

  # DNS domain that all services will either be members of, or, in the
  # case of external-dns and pdns, manage.
  dnsDomain: suse.baremetal

  # specify comma serparate beginning and end of the range of IP
  # addresses the DHCP server will manage.
  dhcpRange: 192.168.20.20,192.168.20.80

  # Network interface on which provisioning network can be accessed
  provisioningInterface: ens4

  # IP Address assigned to network interface on provisioning network
  provisioningIP: 192.168.20.5

  # If using pdnsIP for to set powerdns to use hostNetwork, update
  # the nameservers to the pdnsIP address
  dnsConfig:
    nameservers:
    - 10.43.255.254
    searches:
    - suse.baremetal

  # If running in a multi-node kubernetes cluster, "pin" the baremtal container
  # to the same host where the ironic, external-dns, pdns, and media containers
  # arerunning. Uncomment the nodeSelector and update the hostname accordingly.
  #nodeSelector: 
    #kubernetes.io/hostname: "my-hostname"

  # Comment this out when pinning the baremetal-operator container to a specfic host.
  nodeSelector: {}

replicaCount: 1

image:
  repository: quay.io/metal3-io/baremetal-operator
  pullPolicy: IfNotPresent 
  # Overrides the image tag whose default is the chart appVersion.
  tag: "capm3-v1.1.2"

imagePullSecrets: []
nameOverride: "manger"
fullnameOverride: "baremetal-operator"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "baremetal-operator-controller-manager"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: baremetal-operator.suse.baremetal
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []

affinity: {}

baremetaloperator:
  cacheUrl: "http://cache.ironic.{{ .Values.global.dnsDomain }}/images"
  deployKernelUrl: "http://boot.ironic.{{ .Values.global.dnsDomain }}/images/ironic-python-agent.kernel"
  deployRamdiskUrl: "http://boot.ironic.{{ .Values.global.dnsDomain }}/images/ironic-python-agent.initramfs"
  httpPort: "6180"

  ironicEndpoint: "http://api.ironic.{{ .Values.global.dnsDomain }}/v1/"
  ironicInspectorEndpoint: "http://inspector.ironic.{{ .Values.global.dnsDomain }}/v1/"
