apiVersion: v1
data:
{{- with .Values.baremetaloperator }}
  CACHEURL: {{ .cacheUrl }}
  DEPLOY_KERNEL_URL: {{ .deployKernelUrl }}
  DEPLOY_RAMDISK_URL: {{ .deployRamdiskUrl }}
  HTTP_PORT: {{ .httpPort | quote }}
  IRONIC_ENDPOINT: {{ .ironicEndpoint }}
  IRONIC_INSPECTOR_ENDPOINT: {{ .ironicInspectorEndpoint }}
{{- end }}
  DHCP_RANGE: {{ .Values.global.dhcpRange }}
  PROVISIONING_INTERFACE: {{ .Values.global.provisioningInterface }}
  PROVISIONING_IP: {{ .Values.global.provisioningIP }}
  IRONIC_FAST_TRACK: "true"
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
