{{- if and (.Values.ingress.enabled) (.Values.global.enable_ironic) -}}  
  {{- if and ($.Values.global.enable_tls) (eq .Values.ingress.tlsSource "letsEncrypt") -}}
apiVersion: cert-manager.io/v1 
kind: Issuer
metadata:
  name: {{ include "ironic.fullname" . }}
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
spec:
  {{- $relname := .Release.Name }}      
  acme:
  {{- if eq .Values.letsEncrypt.environment "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
  {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
  {{- end }}  
    email: ''
    privateKeySecretRef:
      name: letsencrypt-private-key 
    solvers:
    - selector:
        dnsNames:
        - "api.ironic.{{ .Values.global.dnsDomain }}"
        - "inspector.ironic.{{ .Values.global.dnsDomain }}"
        - "boot.ironic.{{ .Values.global.dnsDomain }}"
        - "cache.ironic.{{ .Values.global.dnsDomain }}"       
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ include "ironic.fullname" . }}-dns-provider-credentials    
            key: api-token
  {{- end -}}
{{- end -}}  
