{{- if and (.Values.ingress.enabled) (.Values.global.enable_ironic) -}}
  {{- if and ($.Values.global.enable_tls) (eq .Values.ingress.tlsSource "self") -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ironic.fullname" . }}-tls
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
spec:
  ca:
    secretName: ironic-cacert
  {{- end -}}
{{- end -}}
