{{- if and ( .Values.ingress.enabled) (.Values.global.enable_ironic) -}}
  {{- if and ($.Values.global.enable_tls) (eq .Values.ingress.tlsSource "letsEncrypt") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ironic.fullname" . }}-dns-provider-credentials
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
type: Opaque    
stringData:
  api-token: {{ .Values.baremetaloperator.cloudflareApiToken }}     
  {{- end }}
{{- end }}  
